
services:
  - type: web
    name: tourism-ai-project
    env: node
    buildCommand: pnpm install --no-frozen-lockfile
    startCommand: node Server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: MONGODB_URI=mongodb+srv://<mongodbuser>:<mongodbuser>@cluster0.fzicuak.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: MONGO_URI_DEV
        value: MONGODB_URI=mongodb+srv://<mongodbuser>:<mongodbuser>@cluster0.fzicuak.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    autoDeploy: true
